# Generated by Django 6.0.8 on 2026-08-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_enrollment_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_status',
            field=models.CharField(choices=[('enrolled', 'ENROLLED'), ('running', 'RUNNING'), ('completed', 'COMPLETED'), ('dropped', 'DROPPED')], default='enrolled', max_length=50),
        ),
    ]
