# Generated by Django 6.0.8 on 2026-08-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_assignment_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='funded_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
