# Generated by Django 6.0.8 on 2026-08-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_notification_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='description',
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
