# Generated by Django 6.0.8 on 2026-09-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_rename_sponsored_course_sponsorship_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Category',
            new_name='category',
        ),
    ]
